image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install --frozen-lockfile
    command: |
      export $(cat .env | grep -v "#" | xargs)
      MONGODB_HOST=localhost ./apps/artemis-web/scripts/wait-for -h localhost -p ${MONGODB_PORT} -t 0
      MONGODB_HOST=localhost node apps/artemis-web/scripts/query.js
      MONGODB_HOST=localhost LDAP_HOST=localhost yarn run start
  - init: |
      mkdir -p /workspace/data && mongod --dbpath /workspace/data &
      sleep 5
      if [ -f .env ]; then export $(cat .env | sed 's/#.*//g' | xargs); fi
      mongo admin --eval "db.createUser({user:'"$MONGODB_USER"',pwd:'"$MONGODB_PASS"',roles:[{role:'root',db:'admin'}]})"
      killall mongod
    command: mongod --auth --dbpath /workspace/data
ports:
  - port: 4200
    onOpen: open-browser
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
