version: '3.5'
services:
  artemis-web:
    image: artemis-web:latest
    build:
      context: .
      dockerfile: apps/artemis-web/Dockerfile
    restart: always
    container_name: artemis-web
    networks:
      - proxy-net
    env_file:
      - .env
    ports:
      - 4200:4200
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - proxy-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    volumes:
      - ./mongo-data:/data/db
  ldap:
    image: rroemhild/test-openldap:latest
    container_name: ldap
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    name: artemis_network
