version: '3.5'
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: always
    networks:
        - proxy-net
    ports:
        # uncomment both lines for rootless
        # - "8080:8080"
        # - "8443:8443"
        # comment both lines when running rootless
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/certs/:/etc/nginx/certs/

  artemis_web:
    image: artemis-web:latest
    build:
      context: .
      dockerfile: apps/artemis-web/Dockerfile
    restart: always
    container_name: artemis_web
    networks:
      - proxy-net
    env_file:
      - .env
    ports:
      - 4200:4200
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    restart: always
    networks:
      - proxy-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    volumes:
      - ./mongo-data:/data/db
  ldap:
    image: rroemhild/test-openldap:latest
    container_name: ldap
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    name: artemis_network
