version: '3.5'
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: always
    networks:
        - proxy-net
    ports:
        # uncomment both lines for rootless
        # - "8080:8080"
        # - "8443:8443"
        # comment both lines when running rootless
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/certs/:/etc/nginx/certs/

  artemis_web:
    image: artemis-web:latest
    build:
      context: .
      dockerfile: apps/artemis-web/Dockerfile
    restart: always
    container_name: artemis_web
    networks:
      - proxy-net
    environment:
      HASURA_SECRET: "@rt3m1s."
      JWT_SECRET: "44fe431cdc896ccab691ad0599f4e0a12690ce1ededebe57b825823bc6b4d24f"
      DEFAULT_EMAIL: "admin@admin.com"
      DEFAULT_PASS: "admin1234"
      MONGODB_USER: "admin"
      MONGODB_PASS: "pass"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: 27017
      MONGODB_NAME: "artemis-web"
      LDAP_ENABLED: "true"
      LDAP_HOST: "ldap"
      LDAP_PORT: 10389
      LDAP_PROTOCOL: "ldap"
      LDAP_BIND_DN: "cn=admin,dc=planetexpress,dc=com"
      LDAP_BIND_SECRET: "GoodNewsEveryone"
      LDAP_SEARCH_BASE: "ou=people,dc=planetexpress,dc=com"
      LDAP_SEARCH_FILTER: "(mail={{username}})"
      LDAP_SEARCH_ATTRIBUTES: "mail,uid"
      LDAP_GROUP_SEARCH_BASE: "ou=people,dc=planetexpress,dc=com"
      LDAP_GROUP_SEARCH_FILTER: "(member={{dn}})"
      LDAP_GROUP_SEARCH_ATTRIBUTES: "mail,uid"
      LDAP_EMAIL_FIELDNAME: "mail"
      LDAP_ADMIN_GROUP: "admin_staff"
      CONFIG_HOST: "configuration"
      CONFIG_PORT: 3000
      API_HOST: "postgrest"
      API_PORT: "3000"
      DATABASE_HOST: "database"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
      CSRF_SECRET: "P*3NGEEaJV3yUGDJA9428EQRg!ad"
      NEXT_PUBLIC_SYSTEM_VERSION: "latest"
      TESTING: "false"
      SESSION_TIMEOUT: 1800
      NEXT_PUBLIC_INACTIVITY_TIMEOUT: 900
      API_KEY: "29870959469dc320ff80c02dcccaf0a62394459e22e6acfdce7cf40f94281d85"
    ports:
      - 4200:4200
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    restart: always
    networks:
      - proxy-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "pass"
    volumes:
      - ./mongo-data:/data/db
  ldap:
    image: rroemhild/test-openldap:latest
    container_name: ldap
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    name: artemis_network
