version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
  app:
    container_name: artemis-web
    restart: always
    build:
      context: .
      dockerfile: apps/artemis-web/Dockerfile
    env_file:
      - .env
    ports:
      - 4200:4200
    depends_on:
      - mongodb
