version: '3.5'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - proxy-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
  ldap:
    image: rroemhild/test-openldap:latest
    container_name: ldap
    restart: always
    networks:
      - proxy-net
    ports:
      - '10389:10389'
      - '10636:10636'

networks:
  proxy-net:
    name: artemis_network
