name: Cypress E2E

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image: cypress/included:6.6.0
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: pass
      ldap:
        image: rroemhild/test-openldap
        ports:
          - '389:389'
          - '636:636'

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build --prod
      - run: yarn run nx e2e artemis-web-e2e --browser chrome --prod
        env:
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
      - name: 'Upload Artifact'
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          path: dist/cypress
          retention-days: 5