name: dockerhub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./Dockerfile
          push: false
          tags: inspiregroup/artemis-frontend-web:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}